#!/bin/bash
HERE="$(dirname "$(readlink -f "${0}")")"
cd "$HERE/usr/bin"
python3 -m venv .venv --system-site-packages 2>/dev/null || true
source .venv/bin/activate 2>/dev/null || true
pip install -r requirements.txt -q 2>/dev/null || true
exec python3 main.py "$@"
